### ISSUE TITLE
[FEATURE] Add Notification System

### ISSUE THREAD

**Issue by Ayan-10** [the-hit-times/The-HIT-Times-App-Flutter#1]
**Description**
Adding a notification system to the app would be great to get notified when a new post arrives.

**Tasks**
- [ ] User should get a notification when a new post arrives on the server.

**Comment by abhijitmaiti** [comment]
Ok I will look at this problem

**Comment by sauravkum1023** [comment]
saurav here, me and abhijit is going to work on this
